# Generated by Django 3.0.4 on 2020-04-01 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('p_library', '0006_remove_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='socacc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount', verbose_name='Social account'),
        ),
    ]
